# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab46ea84111fe5c4d3c24feeea36051fd6c2b88e6d263162fe99f436fdc1b703f5da19fac1d518d5e44c66acf4763fc2ab9a151c10443837054f4bc0e7a92bc5

test:
  secret_key_base: 2eec2ba96592f65958d18b5069d70fb8fc7e3de3211c8c99e82d338325efda73ca06e17c95a972774d50bcf39837335ec0c5daf3e156bbd8597ca4b894b4b951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
